### ISSUE TITLE
`@agoric/rpc` and `@agoric/web-components` not installed

### ISSUE THREAD

**Issue by anilhelvaci** [samsiegart/simple-game#1]
I've trying to run this repo but faced the problem below;

```js
Error: The following dependencies are imported but could not be resolved:

  @agoric/rpc (imported by /Users/anil/WebstormProjects/agoric-samples/simple-game/src/App.tsx)
  @agoric/web-components (imported by /Users/anil/WebstormProjects/agoric-samples/simple-game/src/App.tsx)

Are they installed?
    at file:///Users/anil/WebstormProjects/agoric-samples/simple-game/node_modules/vite/dist/node/chunks/dep-df561101.js:45705:23
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///Users/anil/WebstormProjects/agoric-samples/simple-game/node_modules/vite/dist/node/chunks/dep-df561101.js:45114:38
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by dckc** [comment]
I haven't run into this problem. Is it gone?
